### ISSUE TITLE
About the GPU mermory

### ISSUE THREAD

**Issue by realwenpeng** [LTTM/UDAclustering#3]
Sorry to disturb you...   I want to know how much GPU memory do I need according to your experiment settings. And my GPU memory is 11GB, did you have a recommended experiment settings....

**Comment by marco-toldo** [comment]
Experiments were performed on a RTX TITAN with 24GB, in the repo you can find the hyperpareters that have been used (we followed the same input preprocessing of other UDA works to be able to compare with them).
However, by reducing the size of input images you can train on a gpu with smaller memory capacity.

**Comment by realwenpeng** [comment]
Thanks，thank you for your respond perfectly reslove my problem.
